const CATALOG_DATA = [
    { slug: 'vela-de-cera', group: 'velas', subcat: 'vela-de-cera', subcatLabel: 'Tornillo', products: [
      { file: 'vela-de-cera-rosa-gold', title: 'Rosa Gold Metálico', ref: '' },
      { file: 'vela-de-crea-oro-champagne', title: 'Oro Champagne Metálico', ref: '' },
      { file: 'vela-de-cera-tinto', title: 'Tinto Metálico', ref: '' },
      { file: 'vela-de-cera-azul', title: 'Azul Metálico', ref: '' },
      { file: 'vela-de-cera-plateada', title: 'Plateado Metálico', ref: '' },
      { file: 'vela-de-cera-colores-plus', title: 'Colores Plus Metálico', ref: '' },
      { file: 'vela-de-cera-colores', title: 'Colores Metálico', ref: '' },
    ] },
    { slug: 'velas-de-cera-numero', group: 'velas', subcat: 'velas-de-cera-numero', subcatLabel: 'Número', products: [
      { file: 'vela-de-cera-de-numero-plateada', title: 'Vela de Cera de Número Plateada', ref: '' },
      { file: 'vela-de-cera-de-numero-dorada-corona', title: 'Vela de Cera de Número Dorada Corona', ref: '' },
      { file: 'vela-de-cera-de-numero-plateada-corona', title: 'Vela de Cera de Número Plateada Corona', ref: '' },
      { file: 'vela-de-cera-de-numero-dorada', title: 'Vela de Cera de Número Dorada', ref: '' },
    ] },
    { slug: 'vela-pirotecnia', group: 'velas', subcat: 'vela-pirotecnia', subcatLabel: 'Pirotécnica', products: [
      { file: 'vela-pirotecnia-rosa', title: 'Vela Pirotecnia Rosa', ref: '' },
      { file: 'velas-pirotecnia-colores', title: 'Velas Pirotecnia Colores', ref: '' },
      { file: 'velas-pirotecnia-paquete', title: 'Velas Pirotecnia Paquete', ref: '' },
    ] },
    { slug: 'velas-de-cera-espiral', group: 'velas', subcat: 'velas-de-cera-espiral', subcatLabel: 'Torcida', products: [
      { file: 'vela-espiral-rosa-gold', title: 'Rosa Gold', ref: '' },
      { file: 'vela-espiral-fushia', title: 'Fushia', ref: '' },
      { file: 'vela-espiral-morada', title: 'Morada', ref: '' },
      { file: 'vela-espiral-negro', title: 'Negro', ref: '' },
      { file: 'vela-espiral-plateado', title: 'Plateado', ref: '' },
      { file: 'vela-espiral-cobre', title: 'Cobre', ref: '' },
      { file: 'vela-espiral-colores-plus', title: 'Colores Plus', ref: '' },
      { file: 'vela-espiral-dorado', title: 'Dorado', ref: '' },
    ] },
    { slug: 'vela-de-cera-creativa', group: 'velas', subcat: 'vela-de-cera-creativa', subcatLabel: 'Rosa', products: [
      { file: 'vela-de-rosas', title: 'Vela de Rosas', ref: '' },
      { file: 'vela-de-rosa-azul', title: 'Vela de Rosa Azul', ref: '' },
    ] },
    { slug: 'velas-cera-feliz-cumpleanos', group: 'velas', subcat: 'velas-cera-feliz-cumpleanos', subcatLabel: 'Feliz Cumpleaños', products: [
      { file: 'velas-de-cera-feliz-cumplanos-1', title: 'Rosa Metálico', ref: '' },
      { file: 'velas-de-cera-feliz-cumplanos-2', title: 'Rosa Gold Metálico', ref: '' },
      { file: 'velas-de-cera-feliz-cumplanos-3', title: 'Cobre Metálico', ref: '' },
      { file: 'velas-de-cera-feliz-cumplanos-4', title: 'Plateado Metálico', ref: '' },
      { file: 'velas-de-cera-feliz-cumplanos-5', title: 'Azul Metálico', ref: '' },
    ] },
    { slug: 'velas-cera-feliz-cumpleanos', group: 'velas', subcat: 'velas-happy-birthday', subcatLabel: 'Happy Birthday', products: [
      { file: 'vela-happy-birthday-dorado', title: 'Dorado Metálico', ref: '' },
      { file: 'vela-happy-birthday-plateado', title: 'Plateado Metálico', ref: '' },
      { file: 'vela-happy-birthday-cobre', title: 'Cobre Metálico', ref: '' },
      { file: 'vela-happy-birthday-rosa', title: 'Rosa Metálico', ref: '' },
      { file: 'vela-happy-birthday-rosa-gold', title: 'Rosa Gold Metálico', ref: '' },
      { file: 'vela-happy-birthday-azul', title: 'Azul Metálico', ref: '' },
      { file: 'vela-happy-birthday-rojo', title: 'Rojo Metálico', ref: '' },
    ] },
    { slug: 'kit-globos-feliz-cumpleanos', group: 'kits', subcat: 'kit-globos-feliz-cumpleanos', subcatLabel: 'Cumpleaños', products: [
      { file: 'kit-globos-futbol-verde-y-tarro-de-cerveza', title: 'Fútbol Verde y Cerveza', ref: '' },
      { file: 'kit-globos-futbol-negro-y-plata-con-playera', title: 'Fútbol Negro y Plata con Playera', ref: '' },
      { file: 'kit-globos-futbol-rosa-con-letrero', title: 'Fútbol Rosa con Letrero', ref: '' },
      { file: 'kit-globos-futbol-verde-con-letrero', title: 'Fútbol Verde con Letrero', ref: '' },
      { file: 'kit-globos-futbol-verde-con-copa-dorada', title: 'Fútbol Verde con Copa Dorada', ref: '' },
      { file: 'kit-globos-futbol-verde-con-muneco', title: 'Fútbol Verde con Muñeco', ref: '' },
      { file: 'kit-globos-elegante-negro-y-dorado-con-mono', title: 'Elegante Negro y Dorado con Moño', ref: '' },
      { file: 'kit-globos-tematica-dulces-y-paletas', title: 'Temática Dulces y Paletas', ref: '' },
      { file: 'kit-globos-tematica-donas-y-helados', title: 'Temática Donas y Helados', ref: '' },
      { file: 'kit-globos-elegante-blanco-y-dorado', title: 'Elegante Blanco y Dorado', ref: '' },
      { file: 'kit-globos-tematica-safari-y-animal-print', title: 'Temática Safari y Animal Print', ref: '' },
      { file: 'kit-globos-elegante-plata-y-blanco-con-letrero-dorados', title: 'Elegante Plata y Blanco con Letrero Dorados', ref: '' },
      { file: 'kit-globos-verde-eucalipto-arena-y-cristal', title: 'Verde Eucalipto, Arena y Cristal', ref: '' },
      { file: 'kit-globos-tematica-mariposas-lavanda-y-oro', title: 'Temática Mariposas Lavanda y Oro', ref: '' },
      { file: 'kit-globos-tematica-monsters-inc', title: 'Temática Monsters Inc', ref: '' },
      { file: 'kit-globos-arcoiris-tonos-pastel', title: 'Arcoíris Tonos Pastel', ref: '' },
      { file: 'kit-globos-elegante-azul-marino-y-oro-cromado', title: 'Elegante Azul Marino y Oro Cromado', ref: '' },
      { file: 'kit-globos-tematica-espacio-y-astronauta', title: 'Temática Espacio y Astronauta', ref: '' },
      { file: 'kit-globos-tematica-minions-con-dorado', title: 'Temática Minions con Dorado', ref: '' },
      { file: 'kit-globos-tematica-buzz-lightyear', title: 'Temática Buzz Lightyear', ref: '' },
      { file: 'kit-globos-tematica-construccion-negro-amarillo-y-oro-cromado', title: 'Temática Construcción Negro, Amarillo y Oro Cromado', ref: '' },
      { file: 'kit-globos-corona-rey-azul-metalico-celeste-y-plata', title: 'Corona Rey Azul Metálico, Celeste y Plata', ref: '' },
      { file: 'corona-de-rey-azul', title: 'Corona de Rey Azul', ref: '' },
      { file: 'rosa-pastel-y-oro-rosa', title: 'Rosa Pastel y Oro Rosa', ref: '' },
      { file: 'sirena-y-conchas-marina', title: 'Sirena y Conchas Marina', ref: '' },
      { file: 'boho-eucalipto-y-arena', title: 'Boho Eucalipto y Arena', ref: '' },
      { file: 'rosa-metalico-y-corazones', title: 'Rosa Metálico y Corazones', ref: '' },
      { file: 'negro-y-rosa-fucsia', title: 'Negro y Rosa Fucsia', ref: '' },
      { file: 'margaritas-amarillo-y-celeste', title: 'Margaritas Amarillo y Celeste', ref: '' },
      { file: 'fiesta-selva-verde-y-dorado', title: 'Fiesta Selva Verde y Dorado', ref: '' },
      { file: 'elegante-azul-marino-y-celeste', title: 'Elegante Azul Marino y Celeste', ref: '' },
      { file: 'tonos-pastel-lila-y-coral', title: 'Tonos Pastel Lila y Coral', ref: '' },
      { file: 'elegante-arena-y-oro', title: 'Elegante Arena y Oro', ref: '' },
      { file: 'blanco-y-plata-cromado', title: 'Blanco y Plata Cromado', ref: '' },
      { file: 'safari-estampados-de-animales', title: 'Safari Estampados de Animales', ref: '' },
      { file: 'margaritas-tonos-pastel', title: 'Margaritas Tonos Pastel', ref: '' },
      { file: 'princesita-sofia-morado', title: 'Princesita Sofía Morado', ref: '' },
      { file: 'negro-y-plata-metalico', title: 'Negro y Plata Metálico', ref: '' },
      { file: 'safari-elegante-negro-y-verde', title: 'Safari Elegante Negro y Verde', ref: '' },
    ] },
    { slug: 'kit-de-globo-revelacion', group: 'kits', subcat: 'kit-de-globo-revelacion', subcatLabel: 'Revelación', products: [
      { file: 'baby-shower-nino-azul-y-blanco', title: 'Niño Azul y Blanco', ref: '' },
      { file: 'revelacion-de-genero-con-cortinas', title: 'Girl o Boy', ref: '' },
      { file: 'elegante-menta-y-dorado-cromado', title: 'Menta y Dorado Cromado', ref: '' },
      { file: 'revelacion-azul-y-rosa-pastel', title: 'Azul y Rosa Pastel', ref: '' },
      { file: 'baby-shower-nina-rosa-y-blanco', title: 'Niña Rosa y Blanco', ref: '' },
      { file: 'baby-shower-azul', title: 'Baby Shower Azul', ref: '' },
    ] },
    { slug: 'kit-de-personaje', group: 'globos', subcat: 'kit-de-personaje', subcatLabel: 'Personaje', products: [
      { file: 'kit-mario-bros', title: 'Vaquero y Astronauta de Juguete', ref: 'Toy Story' },
      { file: 'kit-bowser', title: 'Astronauta Azul de Juguete', ref: 'Toy Story (Buzz Lightyear)' },
      { file: 'kit-yoshi', title: 'Bautizo Angelical Azul', ref: 'Bautizo Azul' },
      { file: 'kit-princesa-peach', title: 'Princesita Rosa con Corazones', ref: 'Niña Princesa Rosa' },
      { file: 'kit-luigi', title: 'Pato Dorado Sonriente', ref: 'Pato Dorado' },
      { file: 'kit-my-little-pony', title: 'Princesa Árabe con Lámpara', ref: 'Aladdín (Jasmín)' },
      { file: 'kit-bella-y-bestia', title: 'Capibara Marrón con Bellota', ref: 'Capibara' },
      { file: 'kit-elsa-frozen', title: 'Fantasma Gris de Fiesta', ref: 'Fantasma de Halloween' },
      { file: 'kit-ana-frozen', title: 'Balones de Fútbol Clásico', ref: 'Fútbol (Balones)' },
      { file: 'kit-olaf-frozen', title: 'Corazones Rosas de Amor', ref: 'Corazones de Amor' },
      { file: 'kit-sirenita-ariel', title: 'Superhéroe Rojo Araña', ref: 'Spiderman' },
      { file: 'kit-flounder', title: 'Cono de Helado Sonriente', ref: 'Cono de Helado' },
      { file: 'kit-cenicienta', title: 'Bautizo Dorado de Niño', ref: 'Bautizo Dorado' },
      { file: 'kit-blancanieves', title: 'Superhéroe Araña en Acción', ref: 'Spiderman' },
      { file: 'kit-moana', title: 'Auto de Carreras Veloz', ref: 'Auto de Carreras' },
      { file: 'kit-bella', title: 'Ratoncita en Auto Rosa', ref: 'Minnie Mouse' },
      { file: 'kit-aurora', title: 'Corona Dorada de Cumpleaños', ref: 'Corona de Cumpleaños' },
      { file: 'kit-rapunzel', title: 'Dragón Negro de Ojos Verdes', ref: 'Cómo Entrenar a tu Dragón (Toothless)' },
      { file: 'kit-jasmine', title: 'Hongo Sonriente con Gorra', ref: 'Mario Bros (Toad)' },
      { file: 'kit-tiana', title: 'Panda Roja Gigante', ref: 'Turning Red (Panda Roja)' },
      { file: 'kit-kuromi', title: 'Princesa Polinesia con Bebé', ref: 'Moana' },
      { file: 'kit-hello-kitty', title: 'Unicornio Arcoíris Mágico', ref: 'Unicornio Arcoíris' },
      { file: 'kit-my-melody', title: 'Osito Panda Blanco y Negro', ref: 'Panda' },
      { file: 'kit-cinnamoroll', title: 'Superhéroe Araña Volador', ref: 'Spiderman' },
      { file: 'kit-badtz-maru', title: 'Ratón Clásico en Auto Rojo', ref: 'Mickey Mouse' },
      { file: 'kit-keroppi', title: 'Gatita Blanca de Moño', ref: 'Hello Kitty' },
      { file: 'kit-pompompurin', title: 'Tortuga Azul de Agua', ref: 'Pokémon (Squirtle)' },
      { file: 'kit-pochacco', title: 'Perrita Azul Juguetona', ref: 'Bluey' },
      { file: 'kit-chococat', title: 'Estrella de Mar Rosada', ref: 'Bob Esponja (Patricio)' },
      { file: 'kit-little-twin-stars', title: 'Cerdita Rosa Sonriente', ref: 'Peppa Pig' },
      { file: 'kit-spiderman', title: 'Cerdita Rosa Bailando', ref: 'Peppa Pig' },
      { file: 'kit-batman', title: 'Ratón Aventurero Azul', ref: 'Bely y Beto' },
      { file: 'kit-superman', title: 'Pato Marinero de Invierno', ref: 'Pato Donald' },
      { file: 'kit-iron-man', title: 'Princesa Polinesia de las Olas', ref: 'Moana' },
      { file: 'kit-capitan-america', title: 'Niña con Gatitos Mágicos', ref: 'Gabby\'s Dollhouse' },
      { file: 'kit-hulk', title: 'Perrito Rescatista en Montaña', ref: 'Paw Patrol (Chase)' },
      { file: 'kit-thor', title: 'Guerrero de Cabello Dorado', ref: 'Dragon Ball (Goku)' },
      { file: 'kit-chase-paw-patrol', title: 'Perrito Rescatista Color Café', ref: 'Paw Patrol (Skye)' },
      { file: 'kit-marshall-paw-patrol', title: 'Trofeo Dorado de Fútbol', ref: 'Fútbol (Barcelona)' },
      { file: 'kit-skye-paw-patrol-01', title: 'Niña de Cumpleaños Morado', ref: 'Niña de Cumpleaños' },
      { file: 'kit-rubble-paw-patrol', title: 'Perrito Rescatista con Arcoíris', ref: 'Paw Patrol (Rubble)' },
      { file: 'kit-futbol', title: 'Balones de Fútbol Rosa', ref: 'Fútbol (Balones)' },
      { file: 'kit-bob-esponja', title: 'Esponja Amarilla Sonriente', ref: 'Bob Esponja' },
      { file: 'kit-rapunzel-princesas', title: 'Dos Princesas de Cuento', ref: 'Disney Princesas (Rapunzel)' },
      { file: 'kit-angel-y-stitch', title: 'Koala Azul Espacial de Fiesta', ref: 'Stitch (Lilo y Stitch)' },
      { file: 'kit-virgen-de-guadalupe', title: 'Virgen de Guadalupe', ref: 'Virgen de Guadalupe' },
      { file: 'kit-minnie-mouse', title: 'Ratoncita de Moño Rojo', ref: 'Minnie Mouse' },
      { file: 'kit-tiburon-gym', title: 'Tiburón Musculoso de Gimnasio', ref: 'Tiburón Gym' },
      { file: 'kit-sonic', title: 'Erizo Azul Corriendo', ref: 'Sonic' },
      { file: 'kit-vaca-animada', title: 'Vaca Sonriente de Granja', ref: 'Vaca (Granja)' },
      { file: 'kit-cebra-animada', title: 'Cebra Sonriente a Rayas', ref: 'Cebra' },
      { file: 'kit-mono-animado', title: 'Mono Sonriente Juguetón', ref: 'Mono' },
      { file: 'kit-skye-paw-patrol-02', title: 'Perrito Rescatista Alegre', ref: 'Paw Patrol (Skye)' },
      { file: 'kit-dinosaurio-t-rex-naranja', title: 'Dinosaurio Naranja Feroz', ref: 'Dinosaurio T-Rex' },
      { file: 'kit-dinosaurio-t-rex-rojo', title: 'Dinosaurio Rojo Rugiente', ref: 'Dinosaurio T-Rex' },
      { file: 'kit-dinosaurio-triceratops', title: 'Dinosaurio de Tres Cuernos', ref: 'Dinosaurio Triceratops' },
      { file: 'kit-winnie-pooh', title: 'Osito Amarillo Amigable', ref: 'Winnie Pooh' },
      { file: 'kit-rayo-mcqueen', title: 'Auto de Carreras Rojo', ref: 'Cars (Rayo McQueen)' },
      { file: 'kit-futbol-americano', title: 'Balón de Fútbol Americano', ref: 'Fútbol Americano' },
      { file: 'kit-baloncesto', title: 'Balones Anaranjados de Baloncesto', ref: 'Baloncesto' },
      { file: 'plim-plim', title: 'Conejita Gótica de Cabello Azul', ref: 'Kuromi' },
      { file: 'malefica', title: 'Conejita Gótica Blanca', ref: 'Kuromi' },
      { file: 'los-increibles', title: 'Familia de Vacas Sonrientes', ref: 'Vaca (Granja)' },
      { file: 'cruella-de-vil', title: 'Erizo y Zorro Veloces', ref: 'Sonic (con Tails)' },
      { file: 'aladdin-jasmin', title: 'Gatita Blanca de Moño Rosa', ref: 'Hello Kitty' },
      { file: 'pocahontas', title: 'Koala Azul Espacial Estelar', ref: 'Stitch (Lilo y Stitch)' },
      { file: 'mulan', title: 'Perrito Bombero Rojo', ref: 'Paw Patrol (Marshall)' },
      { file: 'tiana-la-princesa-y-el-sapo', title: 'Robot Transformable Amarillo', ref: 'Transformers (Bumblebee)' },
      { file: 'merida-valiente', title: 'Arcoíris Feliz con Nubes', ref: 'Arcoíris' },
      { file: 'moana', title: 'Princesa Amarilla de Cuento', ref: 'Disney Princesas (Bella)' },
      { file: 'raya-el-ultimo-dragon', title: 'Llantas de Carreras Veloces', ref: 'Llantas de Carreras' },
      { file: 'mirabel-encanto', title: 'Despedida de Soltera Morada', ref: 'Despedida de Soltera' },
      { file: 'asha-wish-el-poder-de-los-deseos', title: 'Radio de Fiesta Colorida', ref: 'Radio de Fiesta' },
      { file: 'intensamente-ansiedad', title: 'Piña Tropical de Verano', ref: 'Piña Tropical' },
      { file: 'naruto-diseno-clasico-shippuden', title: 'Corona Dorada Real', ref: 'Corona de Cumpleaños' },
      { file: 'one-piece-luffy', title: 'Conejita Gótica Rosa', ref: 'Kuromi' },
      { file: 'dragon-ball-goku', title: 'Sirena de Cola Verde', ref: 'La Sirenita (Ariel)' },
      { file: 'demon-slayer-tanjiro', title: 'Osito Amigable con Miel', ref: 'Winnie Pooh' },
      { file: 'my-hero-academia-deku', title: 'Fontanero Verde con Gorra', ref: 'Mario Bros (Luigi)' },
      { file: 'jujutsu-kaisen-gojo', title: 'Niña con Oso de Peluche', ref: 'Masha y el Oso' },
      { file: 'minecraft', title: 'Fontanero Rojo con Gorra', ref: 'Mario Bros' },
      { file: 'fortnite', title: 'Payasito Rosa de Circo', ref: 'Plim Plim' },
      { file: 'pokemon-pikachu', title: 'Koala Azul Espacial Curioso', ref: 'Stitch (Lilo y Stitch)' },
      { file: 'super-mario-bros-luigi', title: 'Bebé Rosa Consentida', ref: 'Bebé (Niña)' },
      { file: 'bowser-super-mario-bros', title: 'Bebé Azul Dormilón', ref: 'Bebé (Niño)' },
      { file: 'yoshi-super-mario-bros', title: 'Ratoncita de Lunares Rosa', ref: 'Minnie Mouse' },
      { file: 'toad-honguito-super-mario-bros', title: 'Perrita Azul de Caricatura', ref: 'Bluey' },
      { file: 'princesa-peach-super-mario-bros', title: 'Fútbol Campeón de Cumpleaños', ref: 'Fútbol (Barcelona)' },
      { file: 'rosita-fresita', title: 'Ratón Clásico con Guante Blanco', ref: 'Mickey Mouse' },
      { file: 'monster-high', title: 'Bebé Risueño de Mejillas Rojas', ref: 'Plim Plim' },
      { file: 'princesita-sofia', title: 'Princesita Morada con Castillo', ref: 'Sofía la Princesa' },
      { file: 'sonic', title: 'Erizo Azul con Amigo Pato', ref: 'Sonic' },
      { file: 'motociclista-de-carreras-moto-azul', title: 'Motociclista de Carreras Veloz', ref: 'Motociclista de Carreras' },
      { file: 'spider-man', title: 'Superhéroe Araña de Cerca', ref: 'Spiderman' },
      { file: 'granja-gallo', title: 'Gallo de Granja Cantor', ref: 'Gallo (Granja)' },
      { file: 'princesa-aurora-la-bella-durmiente', title: 'Princesa Rosa con Corona', ref: 'Aurora (La Bella Durmiente)' },
      { file: 'capibara', title: 'Capibara con Sombrero de Fiesta', ref: 'Capibara' },
      { file: 'cenicienta', title: 'Princesa Azul de Cristal', ref: 'Cenicienta' },
      { file: 'blancanieves', title: 'Princesa del Bosque Amarilla', ref: 'Blancanieves' },
      { file: 'bandera-de-mexico', title: 'Bandera de México Tricolor', ref: 'Bandera de México' },
      { file: 'naruto-estilo-chibi', title: 'Ninja Anaranjado Saltando', ref: 'Naruto' },
      { file: 'changuito-mono-de-cumpleanos', title: 'Changuito Feliz de Cumpleaños', ref: 'Changuito (Mono)' },
      { file: 'iron-man', title: 'Héroe de Armadura Dorada', ref: 'Iron Man' },
      { file: 'cono-de-helado-happy-birthday', title: 'Cono de Helado de Cumpleaños', ref: 'Cono de Helado' },
      { file: 'malteada-frappe', title: 'Malteada Dorada Espumosa', ref: 'Malteada' },
      { file: 'mariposa', title: 'Mariposa Colorida Volando', ref: 'Mariposa' },
      { file: 'barbie-letrero-logo', title: 'Muñeca de Moda Rosa', ref: 'Barbie' },
      { file: 'barbie-en-carro-rosa', title: 'Muñeca en Auto Deportivo Rosa', ref: 'Barbie' },
      { file: 'primera-comunion-azul-on-your-communion', title: 'Primera Comunión Azul con Cruz', ref: 'Primera Comunión Azul' },
      { file: 'pato-donald', title: 'Pato Marinero Clásico', ref: 'Pato Donald' },
      { file: 'primera-comunion-rosa-on-your-communion', title: 'Primera Comunión Rosa con Cruz', ref: 'Primera Comunión Rosa' },
      { file: 'roblox', title: 'Personajes de Bloques Aventureros', ref: 'Roblox' },
      { file: 'toy-story-woody', title: 'Vaquero de Juguete Sonriente', ref: 'Toy Story (Woody)' },
      { file: 'caballos-rosa-y-negro', title: 'Caballitos Rosa y Negro', ref: 'Caballos' },
      { file: 'kuromi', title: 'Conejita Gótica Nocturna', ref: 'Kuromi' },
    ] },
    { slug: 'kit-globlos-boda', group: 'kits', subcat: 'kit-globlos-boda', subcatLabel: 'Boda', products: [
      { file: 'nuestra-boda-blanco-y-oro', title: 'Blanco y Oro', ref: '' },
    ] },
    { slug: 'kit-globo-te-amo', group: 'kits', subcat: 'kit-globo-te-amo', subcatLabel: 'Te Amo', products: [
      { file: 'te-amo-tono-rosa-y-cafe', title: 'Tono Rosa y Café', ref: '' },
      { file: 'te-amo-fucsia-y-negro', title: 'Fucsia y Negro', ref: '' },
    ] },
    { slug: 'kit-de-globos-graduacion', group: 'kits', subcat: 'kit-de-globos-graduacion', subcatLabel: 'Graduación', products: [
      { file: 'feliz-graduacion-azul-marino-y-oro', title: 'Azul Marino y Oro', ref: '' },
    ] },
    { slug: 'globo-de-letras', group: 'globos', subcat: 'globo-de-letras', subcatLabel: 'Letra', products: [
      { file: 'feliz-cumpleanos-oro', title: 'Feliz Cumpleaños Oro', ref: '' },
      { file: 'feliz-cumpleanos-plata-02', title: 'Feliz Cumpleaños Plata', ref: '' },
      { file: 'feliz-cumpleanos-negro', title: 'Feliz Cumpleaños Negro', ref: '' },
      { file: 'feliz-cumpleanos-tono-pastel', title: 'Feliz Cumpleaños Tono Pastel', ref: '' },
      { file: 'feliz-cumpleanos-rosa', title: 'Feliz Cumpleaños Rosa', ref: '' },
      { file: 'feliz-cumpleanos-rojo', title: 'Feliz Cumpleaños Rojo', ref: '' },
      { file: 'feliz-cumpleanos-morado', title: 'Feliz Cumpleaños Morado', ref: '' },
      { file: 'feliz-cumpleanos-plata-01', title: 'Feliz Cumpleaños Plata Cursiva', ref: '' },
      { file: 'feliz-cumpleanos-multicolor', title: 'Feliz Cumpleaños Multicolor', ref: '' },
      { file: 'feliz-cumpleanos-dorado-cursiva', title: 'Feliz Cumpleaños Dorado Cursiva', ref: '' },
      { file: 'feliz-cumpleanos-negro-cursiva', title: 'Feliz Cumpleaños Negro Cursiva', ref: '' },
      { file: 'feliz-cumpleanos-habile-oro', title: 'Feliz Cumpleaños Oro/Plata Brillante', ref: '' },
      { file: 'happy-birthday-plata-cursiva', title: 'Happy Birthday Plata Cursiva', ref: '' },
      { file: 'mis-15-anos-oro', title: 'Mis 15 Años Oro', ref: '' },
      { file: 'mi-bautizo-oro', title: 'Bautizo Oro', ref: '' },
      { file: 'mi-bautizo-plata', title: 'Bautizo Plata', ref: '' },
      { file: 'primera-comunion-oro', title: 'Primera Comunión Oro', ref: '' },
      { file: 'primera-comunion-plata', title: 'Primera Comunión Plata', ref: '' },
      { file: 'bienvenido-oro-01', title: 'Bienvenido Oro', ref: '' },
      { file: 'bienvenido-oro-02', title: 'Bienvenido Oro', ref: '' },
      { file: 'bienvenido-plata', title: 'Bienvenido Plata', ref: '' },
    ] },
    { slug: 'globos-comunes', group: 'globos', subcat: 'globos-comunes', subcatLabel: 'Látex', products: [
      { file: 'paquete-globos-de-latex-colores-surtidos-1', title: 'Látex Surtidos 1', ref: '' },
      { file: 'paquete-globos-de-latex-colores-surtidos-2', title: 'Látex Surtidos 2', ref: '' },
    ] },
    { slug: 'arreglo-para-globo', group: 'globos', subcat: 'arreglo-para-globo', subcatLabel: 'Arreglo', products: [
      { file: 'kit-arreglo-de-globo-luminoso-con-rosa', title: 'Globo Luminoso con Rosa', ref: '' },
    ] },
    { slug: 'feliz-aniversario', group: 'kits', subcat: 'feliz-aniversario', subcatLabel: 'Aniversario', products: [
      { file: 'kit-de-arco-de-globos-happy-anniversary-negro-con-oro', title: 'Negro con Oro', ref: '' },
      { file: 'kit-de-arco-de-globos-happy-anniversary-plata-con-blanco', title: 'Plata con Blanco', ref: '' },
    ] },
    { slug: 'banderin', group: 'banderines', subcat: 'banderin-diamantina', subcatLabel: 'Diamantado', products: [
      { file: 'banderin-dorado-adiamantado-letras-plata', title: 'Dorado', ref: '' },
      { file: 'banderin-plateado-adiamantado-letras-oro', title: 'Plateado', ref: '' },
      { file: 'banderin-negro-adiamantado-letras-oro', title: 'Negro', ref: '' },
      { file: 'banderin-rosa-adiamantado-letras-oro', title: 'Rosa', ref: '' },
      { file: 'banderin-fucsia-adiamantado-letras-oro', title: 'Fucsia', ref: '' },
      { file: 'banderin-rojo-adiamantado-letras-oro', title: 'Rojo', ref: '' },
      { file: 'banderin-azul-adiamantado-letras-oro', title: 'Azul', ref: '' },
      { file: 'banderin-morado-adiamantado-letras-oro', title: 'Morado', ref: '' },
      { file: 'banderin-verde-adiamantado-letras-oro', title: 'Verde', ref: '' },
    ] },
    { slug: 'banderin', group: 'banderines', subcat: 'banderin-holografico', subcatLabel: 'Holográfico', products: [
      { file: 'banderin-rosa-holografico-letras-oro', title: 'Rosa', ref: '' },
      { file: 'banderin-rojo-holografico-letras-oro', title: 'Rojo', ref: '' },
      { file: 'banderin-azul-holografico-letras-oro', title: 'Azul', ref: '' },
      { file: 'banderin-morado-holografico-letras-oro', title: 'Morado', ref: '' },
    ] },
    { slug: 'banderin', group: 'banderines', subcat: 'banderin-liso', subcatLabel: 'Liso', products: [
      { file: 'banderin-liso-blanco', title: 'Blanco', ref: '' },
      { file: 'banderin-liso-negro', title: 'Negro', ref: '' },
      { file: 'banderin-liso-rosa', title: 'Rosa', ref: '' },
      { file: 'banderin-liso-magenta', title: 'Magenta', ref: '' },
      { file: 'banderin-liso-durazno', title: 'Durazno', ref: '' },
      { file: 'banderin-liso-azul', title: 'Azul', ref: '' },
      { file: 'banderin-liso-celeste', title: 'Celeste', ref: '' },
      { file: 'banderin-liso-lila', title: 'Lila', ref: '' },
    ] },
    { slug: 'banderin', group: 'banderines', subcat: 'banderin-baby-shower', subcatLabel: 'Baby Shower', products: [
      { file: 'banderin-liso-baby-shower-corazon-rosa', title: 'Corazón Rosa', ref: '' },
      { file: 'banderin-liso-baby-shower-corazon-azul', title: 'Corazón Azul', ref: '' },
    ] },
    { slug: 'mantel-metalico-para-mesa', group: 'manteles', subcat: 'manteles-metalicos', subcatLabel: 'Metálico', products: [
      { file: 'mantel-foil-desechable-negro-oro-rosa', title: 'Negro/Oro Rosa', ref: '' },
      { file: 'mantel-foil-desechable-rojo-rosa-pastel', title: 'Rojo/Rosa Pastel', ref: '' },
      { file: 'mantel-foil-desechable-azul-rey-dorado', title: 'Azul Rey/Dorado', ref: '' },
      { file: 'mantel-foil-desechable-azul-cielo-fucsia', title: 'Azul Cielo/Fucsia', ref: '' },
      { file: 'mantel-foil-desechable-verde-plata', title: 'Verde/Plata', ref: '' },
    ] },
    { slug: 'mantel-para-mesa', group: 'manteles', subcat: 'manteles', subcatLabel: 'Liso', products: [
      { file: 'mantel-plastico-reusable-oro', title: 'Oro Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-plata', title: 'Plata Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-blanco', title: 'Blanco Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-negro', title: 'Negro Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-amarillo', title: 'Amarillo Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-naranja', title: 'Naranja Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-rosa', title: 'Rosa Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-rosa-pastel', title: 'Rosa Pastel Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-salmon', title: 'Salmón Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-morado', title: 'Morado Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-lila', title: 'Lila Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-verde', title: 'Verde Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-verde-limon', title: 'Verde Limón Reusable', ref: '' },
      { file: 'mantel-plastico-reusable-cafe', title: 'Café Reusable', ref: '' },
    ] },
    { slug: 'cortina-cuadrado', group: 'cortinas', subcat: 'cortina-cuadrada', subcatLabel: 'Cuadrada', products: [
      { file: 'cortina-metalica-cuadros-dorado', title: 'Dorado', ref: '' },
      { file: 'cortina-metalica-cuadros-oro-rosa', title: 'Oro Rosa', ref: '' },
      { file: 'cortina-metalica-cuadros-plata', title: 'Plata', ref: '' },
      { file: 'cortina-metalica-cuadros-bronce', title: 'Bronce', ref: '' },
      { file: 'cortina-metalica-cuadros-negro', title: 'Negro', ref: '' },
      { file: 'cortina-metalica-cuadros-amarillo', title: 'Amarillo', ref: '' },
      { file: 'cortina-metalica-cuadros-naranja', title: 'Naranja', ref: '' },
      { file: 'cortina-metalica-cuadros-rosa-pastel', title: 'Rosa Pastel', ref: '' },
      { file: 'cortina-metalica-cuadros-rojo', title: 'Rojo', ref: '' },
      { file: 'cortina-metalica-cuadros-morado', title: 'Morado', ref: '' },
      { file: 'cortina-metalica-cuadros-azul-cielo', title: 'Azul Cielo', ref: '' },
      { file: 'cortina-metalica-cuadros-verde', title: 'Verde', ref: '' },
    ] },
    { slug: 'cortina-cuadrado-chico', group: 'cortinas', subcat: 'cortina-cuadrada-chica', subcatLabel: 'Cuadrada Chica', products: [
      { file: 'cortina-metalica-cuadros-chicos-dorado', title: 'Dorado', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-oro-rosa-morado', title: 'Oro Rosa / Morado', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-plata-dorado', title: 'Plata / Dorado', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-negro-rojo', title: 'Negro / Rojo', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-guinda', title: 'Guinda', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-azul-marino', title: 'Azul Marino', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-azul-rosa', title: 'Azul / Rosa', ref: '' },
      { file: 'cortina-metalica-cuadros-chicos-colores-surtidos', title: 'Colores Surtidos', ref: '' },
    ] },
    { slug: 'espuma', group: 'complementos', subcat: 'espuma', subcatLabel: 'Espuma', products: [
      { file: 'espuma-para-fiesta-colores-surtidos-3', title: 'Espuma para Fiesta Colores Surtidos', ref: '' },
    ] },
    { slug: 'mariposas', group: 'complementos', subcat: 'mariposas', subcatLabel: 'Mariposa', products: [
      { file: 'decoracion-mariposas-3d-colores-surtidos-1', title: 'Decoración Mariposas 3D Colores Surtidos 1', ref: '' },
    ] },
    { slug: 'espantasuegras', group: 'complementos', subcat: 'espantasuegras', subcatLabel: 'Espantasuegras', products: [
      { file: 'espantasuegras-colores-surtidos-1', title: 'Espantasuegras Colores Surtidos 1', ref: '' },
    ] },
    { slug: 'bomba-electrica-para-inflar-globos', group: 'complementos', subcat: 'bombas', subcatLabel: 'Bomba para Inflar', products: [
      { file: 'inflador-electrico-para-globos', title: 'Inflador Eléctrico para Globos', ref: '' },
    ] },
    { slug: 'bomba-manual-para-inflar-globos', group: 'complementos', subcat: 'bombas', subcatLabel: 'Bomba para Inflar', products: [
      { file: 'inflador-manual-para-globos', title: 'Inflador Manual para Globos', ref: '' },
    ] },
    { slug: 'invitaciones', group: 'complementos', subcat: 'invitaciones', subcatLabel: 'Invitación', products: [
      { file: 'invitaciones-infantiles-personajes-surtidos', title: 'Invitaciones Infantiles Personajes Surtidos', ref: '' },
    ] },
    { slug: 'palo-para-pinata', group: 'complementos', subcat: 'palo-pinata', subcatLabel: 'Palo para Piñata', products: [
      { file: 'palo-para-pinata-decorado-colores-surtidos', title: 'Palo para Piñata Decorado Colores Surtidos', ref: '' },
    ] },
    { slug: 'bolsas-para-bolo', group: 'empaque', subcat: 'bolsas-bolo', subcatLabel: 'Bolsa para Bolo', products: [
      { file: 'bolsa-de-bolo-feliz-cumpleanos', title: 'Feliz Cumpleaños', ref: 'Feliz Cumpleaños' },
      { file: 'bolsa-de-bolo-sonic', title: 'Erizo Azul Corriendo', ref: 'Sonic' },
      { file: 'bolsa-de-bolo-dinosaurios', title: 'Dinosaurios Coloridos', ref: 'Dinosaurios' },
      { file: 'bolsa-de-bolo-paw-patrol', title: 'Perritos Rescatistas', ref: 'Paw Patrol' },
      { file: 'bolsa-de-bolo-toy-story', title: 'Vaquero y Astronauta de Juguete', ref: 'Toy Story' },
      { file: 'bolsa-de-bolo-kuromi', title: 'Conejita Gótica', ref: 'Kuromi' },
      { file: 'bolsa-de-bolo-moana', title: 'Princesa Polinesia', ref: 'Moana' },
      { file: 'bolsa-de-bolo-rapunzel', title: 'Princesa de Trenza Dorada', ref: 'Rapunzel' },
      { file: 'bolsa-de-bolo-roblox', title: 'Personajes de Bloques', ref: 'Roblox' },
      { file: 'bolsa-de-bolo-huntrx', title: 'Grupo Musical Coreano', ref: 'Huntrx (KPop Demon Hunters)' },
      { file: 'bolsa-de-bolo-spiderman', title: 'Superhéroe Rojo Araña', ref: 'Spiderman' },
      { file: 'bolsa-de-bolo-stitch', title: 'Koala Azul Espacial', ref: 'Stitch' },
      { file: 'bolsa-de-bolo-sirenita', title: 'Sirena de Cola Verde', ref: 'Sirenita' },
      { file: 'bolsa-de-bolo-superman', title: 'Héroe de Capa Roja', ref: 'Superman' },
      { file: 'bolsa-de-bolo-mario-bros', title: 'Fontanero Rojo', ref: 'Mario Bros' },
      { file: 'bolsa-de-bolo-avengers', title: 'Equipo de Superhéroes', ref: 'Avengers' },
      { file: 'bolsa-de-bolo-avengers-age-of-ultron', title: 'Equipo de Héroes en Batalla', ref: 'Avengers (Age of Ultron)' },
      { file: 'bolsa-de-bolo-vaca', title: 'Vaquita de Granja', ref: 'Vaca' },
      { file: 'bolsa-de-bolo-princesa-peach', title: 'Princesa de Corona Rosa', ref: 'Princesa Peach' },
      { file: 'bolsa-de-bolo-cars', title: 'Auto de Carreras Rojo', ref: 'Cars' },
      { file: 'bolsa-de-bolo-harry-potter', title: 'Mago con Lentes', ref: 'Harry Potter' },
      { file: 'bolsa-de-bolo-masha-y-el-oso', title: 'Niña y Oso', ref: 'Masha y el Oso' },
      { file: 'bolsa-de-bolo-bella', title: 'Princesa de Vestido Amarillo', ref: 'Bella' },
      { file: 'bolsa-de-bolo-princesas-disney', title: 'Dos Princesas de Cuento', ref: 'Princesas Disney' },
      { file: 'bolsa-de-bolo-the-batman', title: 'Héroe Murciélago', ref: 'The Batman' },
      { file: 'bolsa-de-bolo-plim-plim-abeja', title: 'Abejita Amarilla Feliz', ref: 'Plim Plim (Abeja)' },
      { file: 'bolsa-de-bolo-el-chavo-animado', title: 'Niño de Barril', ref: 'El Chavo Animado' },
      { file: 'bolsa-de-bolo-la-granja-de-zenon', title: 'Animales de Granja', ref: 'La Granja de Zenón' },
      { file: 'bolsa-de-bolo-jessie-toy-story', title: 'Vaquera de Juguete', ref: 'Toy Story (Jessie)' },
      { file: 'bolsa-de-bolo-plim-plim-circo', title: 'Payasito de Circo', ref: 'Plim Plim' },
      { file: 'bolsa-de-bolo-cenicienta', title: 'Princesa de Vestido Azul', ref: 'Cenicienta' },
      { file: 'bolsa-de-bolo-plim-plim-abeja-azul', title: 'Abejita Azul Voladora', ref: 'Plim Plim (Abeja Azul)' },
      { file: 'bolsa-de-bolo-minecraft', title: 'Bloques de Videojuego', ref: 'Minecraft' },
      { file: 'bolsa-de-bolo-minnie-mouse', title: 'Ratoncita de Moño', ref: 'Minnie Mouse' },
      { file: 'bolsa-de-bolo-futbol', title: 'Balones de Fútbol', ref: 'Fútbol' },
      { file: 'bolsa-de-bolo-spiderman-felicidades', title: 'Superhéroe Araña Trepando', ref: 'Spiderman' },
      { file: 'bolsa-de-bolo-hello-kitty', title: 'Gatita Blanca de Moño', ref: 'Hello Kitty' },
    ] },
    { slug: 'bolera-de-carton-pequena', group: 'empaque', subcat: 'bolera-carton', subcatLabel: 'Bolera de Cartón', products: [
      { file: 'bolera-de-carton-pequena', title: 'Bolera de Cartón Pequeña', ref: '' },
    ] },
    { slug: 'bolos-carton', group: 'empaque', subcat: 'bolos-carton', subcatLabel: 'Bolo de Cartón', products: [
      { file: 'bolo-de-carton-bely-y-beto', title: 'Payasitos Divertidos', ref: 'Bely y Beto' },
      { file: 'bolo-de-carton-bella-y-bestia', title: 'Princesa y Bestia', ref: 'Bella y Bestia' },
      { file: 'bolo-de-carton-spiderman', title: 'Superhéroe Rojo Araña', ref: 'Spiderman' },
      { file: 'bolo-de-carton-lilo-y-stitch-hula', title: 'Koala Azul Bailando Hula', ref: 'Lilo y Stitch (Hula)' },
      { file: 'bolo-de-carton-dragon-ball-goku', title: 'Guerrero de Cabello Dorado', ref: 'Dragon Ball (Goku)' },
      { file: 'bolo-de-carton-minecraft', title: 'Bloques de Videojuego', ref: 'Minecraft' },
      { file: 'bolo-de-carton-paw-patrol', title: 'Perritos Rescatistas', ref: 'Paw Patrol' },
      { file: 'bolo-de-carton-stitch-feliz-cumple', title: 'Koala Azul de Cumpleaños', ref: 'Stitch (Feliz Cumple)' },
      { file: 'bolo-de-carton-minnie-mouse-roja', title: 'Ratoncita de Moño', ref: 'Minnie Mouse (Roja)' },
      { file: 'bolo-de-carton-hello-kitty-feliz-cumple', title: 'Gatita Blanca de Moño', ref: 'Hello Kitty' },
      { file: 'bolo-de-carton-kuromi-feliz-cumple', title: 'Conejita Gótica', ref: 'Kuromi' },
      { file: 'bolo-de-carton-masha-y-el-oso', title: 'Niña y Oso', ref: 'Masha y el Oso' },
      { file: 'bolo-de-carton-labubu', title: 'Duende Peludo Sonriente', ref: 'Labubu' },
    ] },
    { slug: 'toppers', group: 'complementos', subcat: 'toppers', subcatLabel: 'Topper', products: [
      { file: 'feliz-cumpleanos-madera', title: 'Feliz Cumpleaños Madera', ref: '' },
    ] }
  ];